### PR TITLE
Ihasan/footprints v20

### PR DESCRIPTION
**Pull request by ih64**
this PR updates the Footprints.ipynb so it works for v20 of the LSST Pipelines

### CODE REVIEW

**Comment by kadrlica** [comment]
@ih64 did you commit the compiled notebook by accident? Maybe a rebase is needed to roll back this commit.

**Comment by kadrlica** [comment]
Or alternatively, close this PR and make a new one without the compiled commit?

**Comment by ih64** [comment]
whoops, sorry about that @kadrlica , my mistake. I added another commit clearing out the output. When I go to 'Files Changed' it looks like the un-compiled version is there now.

**Comment by kadrlica** [comment]
Thanks @ih64. I think the issue is that the previous commit is still in the PR, so it would be merged into the tree with this PR. The concern is that the rendered PNGs will bloat the repo size. While we aren't strict about this, I was thinking that we'd want a new PR with just the uncompiled version. I can give this a shot tonight and ask you to review it.

**Comment by kadrlica** [comment]
Closing this to open a new PR with the clean notebook.

**Pull request closed without merging**
