### PR TITLE
Project/density maps/jeffcarlin

### PR DESCRIPTION
**Pull request by jeffcarlin**
Hi Nushkia - since you expressed interest in reviewing my Stack Club project a few weeks ago, I have invited you to review. Let me know if you are unable to review this notebook, or if you have any questions about it.

Alex - your comments are welcome as well, but if you want to weigh in after Nushkia, I can ping you then.

### CODE REVIEW

**Comment by kadrlica** [comment]
Thanks Jeff. I'll weigh in after Nushkia (if she is available).

**Review by kadrlica — COMMENTED** [review]
I see this cell
```
! cd ~/stackclub/StackClub/ && python setup.py -q develop --user && cd -
```
I don't think you can use an absolute path like that, since not everyone has the Stack Club notebooks installed in the same place. 

In the FindingDocs notebook (under GettingStarted), Phil does something like this:
```
! cd .. && python setup.py -q develop --user && cd -
```

**Review by kadrlica — COMMENTED** [review]
I see this call to see if a data set exists. Does this actually "guarantee" that the data set is on disk? 
```
butler.datasetExists('deepCoadd_forced_src', dataId=dataref14)
```
I thought there may have been some subtleties here that involved getting the URI

**Review by kadrlica — COMMENTED** [review]
What does `immediate=True` mean here? I hadn't seen that before. Is it worth noting?
```
image14 = butler.get('deepCoadd_calexp', immediate=True, dataId=dataref14)
```

**Review by kadrlica — COMMENTED** [review]
General style comment: do you want to indent you comment strings at the same level as your code? Currently not done in function definitions.

**Comment by kadrlica** [comment]
This was super cool Jeff, thanks for writing it! I'll admit, it does make me a bit scared about semi-resolved dwarf searches, though I assume that the algorithms will be tuned up during commissioning.

**Comment by jeffcarlin** [comment]
> I see this cell
> 
> ```
> ! cd ~/stackclub/StackClub/ && python setup.py -q develop --user && cd -
> ```
> 
> I don't think you can use an absolute path like that, since not everyone has the Stack Club notebooks installed in the same place.
> 
> In the FindingDocs notebook (under GettingStarted), Phil does something like this:
> 
> ```
> ! cd .. && python setup.py -q develop --user && cd -
> ```

Good point - I updated it to the relative path.

**Comment by jeffcarlin** [comment]
> I see this call to see if a data set exists. Does this actually "guarantee" that the data set is on disk?
> 
> ```
> butler.datasetExists('deepCoadd_forced_src', dataId=dataref14)
> ```
> 
> I thought there may have been some subtleties here that involved getting the URI

I added the following to the notebook to clarify:

"Note, however, that in the Gen2 butler, this doesn't guarantee that the catalog actually exists as a file on disk. It only tells us that some processing steps were executed that intended to create the catalog, and thus added its entry to the registry. This issue will be remedied in the Gen3 butler, so it is not important to dwell on it further."

**Comment by jeffcarlin** [comment]
> What does `immediate=True` mean here? I hadn't seen that before. Is it worth noting?
> 
> ```
> image14 = butler.get('deepCoadd_calexp', immediate=True, dataId=dataref14)
> ```

Indeed, that was a holdover to ancient times, but unnecessary now. See [this community post](https://community.lsst.org/t/butler-get-now-retrieves-immediately-by-default/1620)

**Review by kadrlica — APPROVED** [review]

**Comment by kadrlica** [comment]
@jeffcarlin want to merge? This notebook is a nice holiday present!

**Pull request merged**
