### PR TITLE
Project/footprints/ishasan

### PR DESCRIPTION
**Pull request by ih64**
- fixing grammatical 
- errors and rephrasing the more technical markdown cells so that we avoid using jargon,
- stay focused on the main goals of the notebooks-instead of going on small tangents.

### CODE REVIEW

**Comment by ih64** [comment]
hi @DouglasLeeTucker, would you mind reviewing my PR? It should be quick, there are only changes in the markdown cells.

**Comment by DouglasLeeTucker** [comment]
Dear Imran,

I would be happy to review your PR, but I am kind of swamped today.
Could I do so on Monday?
Thanks!

Best regards,
Douglas


--
=======================================================================
Douglas L. Tucker
Fermilab                        Tel:    +1-630-840-2267
MS 127                          FAX:    +1-630-840-8274
PO Box 500                      E-mail: dtucker@fnal.gov
Batavia, IL 60510 USA           http://home.fnal.gov/~dtucker/
=======================================================================

**Comment by ih64** [comment]
Hi @DouglasLeeTucker ,

yes of course! thanks Doug :)

**Comment by kadrlica** [comment]
@ih64 you are free to merge!

**Pull request merged**
