### PR TITLE
Updating afw table guided tour to v20

### PR DESCRIPTION
**Pull request by kadrlica**
@ih64 here is my first pass. It would be very appreciated if you could give it a look and decide what you want to do about the cross-catalog section.

Working toward #236.

### CODE REVIEW

**Comment by ih64** [comment]
Hi @kadrlica, I refactored the cross-catalog section so it is using HSC data from two different filters of the same tract/patch, as you suggested. If it looks ok to you, I can review and merge it

**Comment by kadrlica** [comment]
Thanks @ih64. I ran the notebook and it looks very nice. I still don't understand how to access things from a Match object (or really anything about the utility of this object). If you know more about this (and it would be quick), maybe demonstrating how to make a color-magnitude diagram would be useful? 

If this is complex or novel, then I'd approve/merge this notebook and we can come back to it after the PCW.

**Comment by ih64** [comment]
hey @kadrlica, I added the color magnitude diagram example in the matching catalogs section, thanks for the suggestion! If everything looks ok to you I'll review and merge into master

**Comment by kadrlica** [comment]
@ih64 looks great! Please review and merge.

At some point we may want to return to the loop that accesses the magnitude for each entry. Unless there is some C++ magic happening in the background, this doesn't seem very feasible for catalogs containing millions of entries.

**Pull request merged**
