### PR TITLE
Visualizing LSST Camera Geometry

### PR DESCRIPTION
**Pull request by kadrlica**
This PR completes the project described in #202 to explore LSST camera geometry representations and produce an updated version of the LSST focal plane plot. 

A version of the updated figure can be found here:
image

@SimonKrughoff maybe you can suggest a DM expert that could help review this?

### CODE REVIEW

**Comment by kadrlica** [comment]
@SimonKrughoff would you be willing to review this? Just trying to move this PR along after a year of waiting for review.

**Comment by SimonKrughoff** [comment]
Good grief.  So sorry for not noticing this.

**Comment by kadrlica** [comment]
Thanks so much @SimonKrughoff (this hasn't been waiting on you, I just called you in as a backup reviewer). 

Feel free to commit directly to the branch and I can take a look at Stack Club on Friday.

**Comment by kadrlica** [comment]
Trying to run on v20 and got this error (debugging now)
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-6-51ab0ffbeaa0> in <module>
      5 
      6 # Get the amps for this detector
----> 7 amps = det.getAmpInfoCatalog()
      8 
      9 fig,ax = plt.subplots(1,figsize=(10,10))

AttributeError: 'lsst.afw.cameraGeom.detector.detector.Detector' object has no attribute 'getAmpInfoCatalog'
```

**Comment by kadrlica** [comment]
Changed `amps = det.getAmpInfoCatalog` to `amps = det.getAmplifiers()`.

**Comment by kadrlica** [comment]
image

**Pull request merged**
