### PR TITLE
Improved docs for git / github 

### PR DESCRIPTION
**Pull request by Madejski**
Not yet ready for review
I am using this branch to improve the documentation for "getting started" - but more to come!

### CODE REVIEW

**Comment by Madejski** [comment]
Should we assign this one to Sahar?  Since this is now older than the additions you made today - she might have to do a merge, a good learning step...

**Comment by drphilmarshall** [comment]
@Madejski I think it's up to you (as developer) to resolve the conflicts in the file. It looks like you can use the "Resolve Conflicts" button to do this: it'll open up a special editor, that shows you where the conflicts are, and helps you edit the file till there are no conflicts. You need to do this quite carefully to make sure that the ipynb file will still function: make sure you don't delete any lines by mistake, and try to check that the yaml code looks right (and there are no missing brackets, hanging commas etc etc). Good luck!

**Comment by Madejski** [comment]
OK, will do.  I am getting more and more confident with git, but not 100% there yet...  If I follow your instructions as you wrote above, is there a way I can check it i a git window to see whether it runs _without_ reloading it back to my instance of JupyterLab?

**Comment by Madejski** [comment]
I think I removed the conflicts, and also changed the incorrect URL that we identified some time ago.  I assigned you, @drphilmarshall  to review - I hope this is the correct process...

**Comment by kadrlica** [comment]
I tried to load HelloWorld.ipynb and I got the error
```
File Load Error for HelloWorld.ipynb
Unreadable Notebook: /home/kadrlica/notebooks/StackClub/GettingStarted/HelloWorld.ipynb NotJSONError('Notebook does not appear to be JSON: \'{\\n "cells": [\\n {\\n "cell_type": "m...',)
```

**Pull request merged**
