### PR TITLE
Verify LSB notebook on v18.0.0

### PR DESCRIPTION
**Pull request by kadrlica**
This is a trivial update to verify that this notebook runs on v18.0.0.

### CODE REVIEW

**Comment by kadrlica** [comment]
@DouglasLeeTucker would you be willing to review this easy PR?

**Comment by DouglasLeeTucker** [comment]
Yep, would be happy to do so!

But it looks like GitHub is having some issues this morning (see attached GitHub status page).  I will try again later today.

Thanks!

Best regards,
Douglas


--
=======================================================================
Douglas L. Tucker
Fermilab                        Tel:    +1-630-840-2267
MS 127                          FAX:    +1-630-840-8274
PO Box 500                      E-mail: dtucker@fnal.gov
Batavia, IL 60510 USA           http://home.fnal.gov/~dtucker/
=======================================================================

**Comment by kadrlica** [comment]
@DouglasLeeTucker just checking on the status of this. I'd like to get this PR merged before the LSST PCW next week.

Thanks!
Alex

**Comment by DouglasLeeTucker** [comment]
Sorry for the delay, @kadrlica !  I'll work on it this afternoon.  Thanks!

**Comment by kadrlica** [comment]
Thanks @DouglasLeeTucker!

**Pull request merged**
